### ISSUE TITLE
Feature Request: A panel like spacemacs to make it more easy to view commands

### ISSUE THREAD

**Issue by kilon** [michaelgriscom/LeaderMode#34]
This is a question/ feature request, I would like to see a panel like spacemacs because its currently easy to run out of space in the status bar.  Maybe use the side-panels like GitLens is doing ? At least for help or maybe add a way to display all available shortcuts in a cheat sheet of some kind.

I love this addon by the way, thank you very much for making my lifer easier, awesome work

**Comment by michaelgriscom** [comment]
Thanks for the feedback, that's a great suggestion! When I first implemented this I didn't see any great alternatives but I imagine the extension API has changed a bit since then

I'll try to make some time to investigate this before the end of the year and see what all would be involved in improving it
